OPM/IFEM-Poisson

SIMPoisson.h
Goes along [IFEM PR #124](https://github.com/OPM/IFEM/pull/124)
and [IFEM-Darcy PR #3](https://github.com/OPM/IFEM-Darcy/pull/3)
=> Dumps gradient of primary solution to vtf file

main_Poisson.C
Downstream of https://github.com/OPM/IFEM/pull/137
=> adjust to upstream restarting changes

SIMPoisson.h, main_Poisson.C
=> Output refactor

Poisson.C, Poisson.h, Test/Waterfall3D_adap.reg, Test/interior_layer_adap.reg
=> Changed: No external energy due to reaction forces in adaptive simulations

Poisson.h, PoissonSolutions.h, SIMPoisson.h
=> Fix errors / warnings from static analyzers 

CMakeLists.txt, Test/MPI/Cube-3-LR.reg, Test/MPI/Cube-3-LR.xinp, Test/MPI/Square-2-LR.reg, Test/MPI/Square-2-LR.xinp
Downstream of https://github.com/OPM/IFEM/pull/168
=> added: parallel LR tests

Test/lshape-r2-3patch-LR-adap.reg
To go along [IFEM PR#207](https://github.com/OPM/IFEM/pull/207)
=> Updated regression test with increased (LR) multipatch refinement footprint

Test/lshape-r2-3patch-LR-adap.reg
update multi-patch regression test after code change in main library
=> once more for the guys in the back

Poisson.C, SIMPoisson.h
also fix printout for the residual estimator
=> fixed: norm printout after changes in AdaptiveSIM

SIMPoisson2D.C, SIMPoisson3D.C
Downstream of https://github.com/OPM/IFEM/pull/216
=> Anasol fields

Poisson.C, SIMPoisson.h, SIMPoisson1D.C, SIMPoisson2D.C, SIMPoisson3D.C, Test/interior_layer_adap.reg
=> Miscellaneous updates

Test/lshape-r2-3patch-LR-adap.reg, Test/lshape-r2-3patch-LR-adap.xinp
Also simplified the input file a bit.
=> Updated the adaptive multi-patch test due to workaround fix in the main library

SIMPoisson.h, Test/lshape-r2-3patch-LR-adap.reg, main_Poisson.C
Downstream of OPM/IFEM#236 + some cleaning/fixing in SIMPoisson
=> Using SIMSolverstat

Test/lshape-r2-3patch-LR-adap.reg
=>  Changed: Regression update due to revert of workaround fix in main library

Poisson.C
=> Added: Argument partID in the writeVectors method

Test/MPI/Cube.reg, Test/MPI/Square.reg
=> Removed error message from reg-files. It will go away soon.

Test/Square.vreg, Test/Square.xinp
Downstream of https://github.com/OPM/IFEM/pull/360
=> add explicit function output to vtf test

Test/Square-eig1.hreg, Test/Square-eig4.hreg
Downstream of https://github.com/OPM/IFEM/pull/365
=> update hdf5 regtests with eigensolves

main_Poisson.C
Downstream of https://github.com/OPM/IFEM/pull/433
=> solver template update - pass appropriate ProcessAdm

Poisson.C
=> Changed: Remove argument partID again

Poisson.C
buffer is too small to fit a full size_t
=> fixed: sprintf warning

SIMPoisson.C, SIMPoisson.h
=> Changed: newLHS removed in solveSystem method

Poisson.C, Poisson.h, Test/interior_layer_adap.reg, Test/interior_layer_adap_dorfel.reg, Test/interior_layer_adap_rec.reg, Test/interior_layer_adap_res.reg, Test/interior_layer_adap_symmetrized.reg
=> Reaction force fixes (for problems with neumann conditions)

Poisson.C, Poisson.h, SIMPoisson.C
=> Rename setReactionIntegral to setSecondaryInt and use SIMbase::assembleForces

Poisson.C, Poisson.h, SIMPoisson.C, SIMPoisson.h
Downstream of https://github.com/OPM/IFEM/pull/661
=> changed: tinyxml -> tinyxml2

Test/Cube-robin.reg, Test/Sinus2D.reg, Test/Square-robin.reg, Test/lshape-r2-3patch-LR-adap.reg
Downstream of https://github.com/OPM/IFEM/pull/667
=> adjust regression tests for anasol print

Poisson.C, SIMPoisson.h
=> Use RealArray as type for reaction force container

CMakeLists.txt, PoissonSource.C, PoissonSource.h, SIMPoisson.C, SIMPoisson.h, Test/Cube.xinp
=> added: support source function derived from analytical solution

SIMPoisson.C
Downstream of https://github.com/OPM/IFEM/pull/814
=> prefix LR include paths with LR/

Test/TestSIMPoisson.C
Downstream of https://github.com/OPM/IFEM/pull/810
=> convert unit-tests to catch

Test/TestSIMPoisson.C
Downstream of https://github.com/OPM/IFEM/pull/818
=> add support for catch2 v2
